name: travel_byte
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  adaptive_theme: ^3.3.0
  bloc: ^8.1.2
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/destinations/
    - assets/menu/
    - assets/
